# Generated by Django 2.1.7 on 2019-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisdom',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
