# Generated by Django 2.1.7 on 2019-12-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdom', '0002_wisdom_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toxicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='wisdom',
            name='wisdom_occurrence_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
